name: Update Dependency Graph
on:
  push:
    branches:
      - main # default branch of the project

permissions: {}

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    permissions:
      # The API requires write permission on the repository
      # to submit dependencies
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
