name: Build and test Pekko with Scala 2.13

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-scala-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Compile and run tests on Scala 2.13
        # note that this is not running any multi-jvm tests (yet) because multi-in-test=false
        run: |
          sbt "++ 2.13 test"
